dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
env:
  - ITER8_ANALYTICS_METRICS_BACKEND_URL="http://localhost:9090"
# command to run tests

script:
  - make test
