apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-analytics
  labels:
    name: iter8-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-analytics
  template:
    metadata:
      labels:
        app: iter8-analytics
    spec:
      containers:
        - name: iter8-analytics
          image: "iter8/iter8-analytics:master"
          imagePullPolicy: Always
          env:
            - name: METRICS_BACKEND_CONFIGFILE
              value: "config.yaml"
          resources:
            {}
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap: 
            name: iter8-analytics
