apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data: 
  config.yaml: |
    port: {{ .Values.service.port }}
    metricsBackend:
      url: {{ .Values.metricsBackend.url }}
      auth:
        ca_file: {{ .Values.metricsBackend.authentication.ca_file }}
        insecure_skip_verify: {{ .Values.metricsBackend.authentication.insecure_skip_verify }}
        password: {{ .Values.metricsBackend.authentication.password }}
        token: {{ .Values.metricsBackend.authentication.token }}
        type: {{ .Values.metricsBackend.authentication.type }}
        username: {{ .Values.metricsBackend.authentication.username }}
