name: Multi database and secrets integration test

on: ["pull_request"]

jobs:
  in-cluster-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt-get install -y socat
    - name: Run Kubernetes tools
      uses: stefanprodan/kube-tools@v1
      with:
        kubectl: 1.20.0
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.20.0'
    - run: |
        eval $(minikube docker-env)
        docker build . -t iter8-analytics
        kubectl apply -f iter8_analytics/tests/integration/deployment.yaml
        kubectl apply -f iter8_analytics/tests/integration/metrics-mock.yaml
    - run: |
        # minikube service list
        # minikube service iter8-analytics --url
        kubectl wait deploy iter8-analytics --for condition=available --timeout=30s
        kubectl wait deploy metrics-mock --for condition=available --timeout=30s
        kubectl port-forward svc/iter8-analytics 8080:8080 &
        sleep 3.0
        curl http://localhost:8080/health_check
    - run: |
        # create kubernetes secret for use by iter8-analytics
        kubectl create secret generic test-secret --from-literal=user=abcd --from-literal=pass=efgh
        sleep 10.0
        curl -X POST "http://localhost:8080/v2/aggregated_metrics" -H  "accept: application/json" -H  "Content-Type: application/json" -d @iter8_analytics/tests/integration/data/inputs/metrics1.json > out.json
        cat out.json
        echo "logging iter8 analytics"
        kubectl logs deploy/iter8-analytics
        echo "logging metrics mock"
        kubectl logs deploy/metrics-mock
        cat out.json | jq '.data | ."request-count".data.default.value | tonumber'

    # curl metrics endpoint of analytics with proper metrics inputs... 
    # try proper URLs
    # try improper URLs
    # try with proper headers
    # try without proper headers
    # try proper versions
    # try improper versions
