# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
        pip install -e .
    # - name: Lint with pylint
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     pylint iter8_analytics --reports=y
    - name: Test
      run: make test

  build-and-push:
    # Ensure test job passes before pushing image.
    needs: build-and-test

    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        # registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}
    - name: Get version
      run: |
        tarref=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tagref
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
          echo "VERSION=$(echo $tarref | sed -e 's/^v//')" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == *"master" ]]; then
          echo "VERSION=latest" >> $GITHUB_ENV
        fi
    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: iter8/iter8-analytics:${{ env.VERSION }}
        push: true
